# Generated by Django 5.0 on 2024-01-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Car',
        ),
    ]
